# Generated by Django 2.1.2 on 2018-11-01 14:10

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=shop.models.image_folder),
        ),
    ]
